# 主题设置 - 支持多主题搜索以覆盖跨领域内容
# 可以使用单个主题或主题列表
topics:
  - "Computer Science"
  - "Electrical Engineering and Systems Science"

# 向后兼容：如果只想使用单个主题，可以使用 topic: "Computer Science"

# 类别设置 - 包含机器学习和AI相关类别
categories:
  - "Artificial Intelligence"
  - "Machine Learning"
  - "Systems and Control"
  - "Neural and Evolutionary Computing"

# 相关性阈值 - 降低到6以获取更多相关论文
threshold: 6

# API配置 - 支持自定义API端点
api_config:
  use_custom_api: true  # 设置为false使用OpenAI API
  api_url: "https://api.siliconflow.cn/v1/chat/completions"
  model_name: "Pro/deepseek-ai/DeepSeek-V3"
  # API密钥通过环境变量CUSTOM_API_KEY设置

# 研究兴趣描述 - 详细说明关注的领域和处理要求
interest: |
  I am interested in the following research areas:
  
  **Primary Focus - Analog Circuit Design with ML/AI:**
  1. Machine learning methods for analog circuit design, including layout generation and sizing optimization
  2. Large language models (LLMs) applied to circuit design automation
  3. AI-driven electronic design automation (EDA) tools
  4. Neural networks for circuit parameter optimization
  5. Deep learning approaches for analog circuit synthesis
  
  **Secondary Focus - Optimization Algorithms (Pure Algorithmic Content):**
  1. Reinforcement learning algorithms and novel RL techniques
  2. Bayesian optimization methods and Gaussian processes
  3. Evolutionary algorithms, genetic algorithms, and nature-inspired optimization
  4. Multi-objective optimization techniques
  5. Hyperparameter optimization and automated machine learning (AutoML)
  
  **Output Requirements:**
  - For analog circuit design papers: Provide concise summary of the methodology and results
  - For pure algorithmic papers: Provide detailed explanation of key concepts and comprehensive summary
  - All outputs should be in both Chinese and English (bilingual)
  
  **Not Interested In:**
  - Pure theoretical circuit analysis without ML/AI components
  - Digital circuit design (unless involving ML/AI)
  - Papers focused on specific programming languages or software tools
  - General electronics without design automation aspects