# 测试模式专用配置 - 更宽泛的类别设置确保能找到论文
topics:
  - "Computer Science"

# 类别设置 - 留空以处理所有论文，确保测试模式下有内容
categories: []

# 相关性阈值 - 设置为0以确保在测试模式下能看到结果
threshold: 0

# API配置 - 与正常模式相同
api_config:
  use_custom_api: true
  api_url: "https://api.siliconflow.cn/v1/chat/completions"
  model_name: "Pro/deepseek-ai/DeepSeek-V3"
  # API密钥通过环境变量CUSTOM_API_KEY设置

# 研究兴趣描述 - 简化的测试版本
interest: |
  I am interested in testing the ArXiv Digest system. Please provide relevance scores and analysis for any computer science papers.
  
  **Testing Focus:**
  1. Any machine learning or AI research
  2. Any computer science papers
  3. Focus on functionality validation
  
  **Output Requirements:**
  - Provide brief English summary
  - Provide brief Chinese summary
  - Give relevance score based on general CS interest
  
  **测试说明：**
  这是一个测试配置，用于快速验证系统功能。
  请对任何找到的计算机科学论文进行简要的中英文分析。